<?php
$_['heading_title'] = 'Auto Generate Tool - Fastest Seo Generator';
$_['text_success'] = 'are Autogenerated Successfully!';
$_['text_module'] = 'Modules';
$_['back'] = 'Back';
$_['warning_clear'] = 'Warning: this will clear all previous SEO Keywords!';
$_['warning_clear_tags'] = 'Warning: this will clear all previous tags!';
$_['categories'] = 'Categories:';
$_['information_pages'] = 'Information Pages:';
$_['products'] = 'Products:';
$_['manufacturers'] = 'Manufacturers:';
$_['general_pages'] = 'General Page ';
$_['generate'] = 'Generate';
$_['error_permission'] = 'Warning: You do not have permission to use seo module!';
$_['meta_keywords'] = 'Meta keywords:';
$_['tags'] = 'Tags';
$_['helpauto'] = "<br><h3>1) Check seo report</h3>Get current seo report about products, categories, manufacturers and information pages without click on this page.<br><br><br><h3>2) Check for value with <font color='red'>red color background</font></h3>If you find a report value in red color background it means seo data is missing for that column header value. Click Generate button to make it green color background.<br><br><br><h3>3) Set your pattern & click generate</h3>Pattern is nothing but what you want to use for auto generatiion. If you enter product name and model name as your pattern, seo data will be generated based on product name and model name. So set your pattern and click generate for generating seo.<br><br><br><font color='green'>You can go to <b>seo advanced editor</b> section in menu to further edit the seo data manually.</font>";

// Text

$_['text_description'] = 'Description';
$_['text_pattern'] = 'Enter Pattern';
$_['text_action'] = 'Action';
$_['text_products'] = 'Products';
$_['text_categories'] = 'Categories';
$_['text_manufacturers'] = 'Manufacurers';
$_['text_information_pages'] = 'Information Pages';
$_['clear_seo']                          =          'Clear Seo';
$_['clear_seo_header']                   =          'Clear Seo All in One';
$_['clear_seo_info']                     =          'You can easily Delete all :<br><br>
													- Url keywords [products, categories, manufactures, information]<br>
													- Title [products, categories, information]<br>
													- Meta keywords [products, categories]<br>
													- Meta descriptions [products, categories]<br>
													- Tags [products]<br>
													<br>
													<span style="color:red">A database backup is recommended before using Clear SEO, because you will lose SEO data! It will delete from all languages !</span><br>
													</span>';
$_['text_url_keyword'] = 'Seo Keyword';
$_['text_title'] = 'Meta Title';
$_['text_meta_keywords'] = 'Meta Keywords';
$_['text_meta_description'] = 'Meta Description';
$_['text_tags'] = 'Tags';
$_['text_image_name'] = 'Image Name';

// clear seo
$_['clear_seo_url'] = 'Clear Url Keywords';
$_['clear_seo_title'] = 'Clear Title';
$_['clear_seo_meta_keywords'] = 'Clear Meta Keywords';
$_['clear_seo_meta_desc'] = 'Clear Meta Description';
$_['clear_seo_tag'] = 'Clear Product Tags';
$_['seo_page_keyword'] = 'All Seo keywords has been removed';
$_['seo_page_title'] = 'Tilte has been removed';
$_['seo_page_meta_keyword'] = 'All meta keywords from products and categories has been removed';
$_['seo_page_meta_desc'] = 'All meta description from products and categories has been removed';
$_['seo_page_tag'] = 'All Product tags has been removed';
$_['autogenerate_help'] = 'Note: Generate action will not clear any previous database entries except for Product Image Name!';

//Dynamic success
$_['product_url_keyword'] = 'Product url Keywords';
$_['product_title'] = 'Products Meta Title';
$_['product_meta_keywords'] = 'Product meta Keywords';
$_['product_meta_description'] = 'Product meta Descriptions';
$_['product_tags'] = 'Product Tags';
$_['product_image_name'] = 'Product Image Names';
$_['category_url_keyword'] = 'Categories url Keywords';
$_['category_meta_description'] = 'Categories meta Description';
$_['category_meta_keywords'] = 'Categories meta keywords';
$_['category_title'] = 'Categories Title';
$_['manufacturer_title'] = 'Manufacturers Title';
$_['manufacturer_meta_description'] = 'Manufacturers Meta Description';
$_['manufacturer_meta_keywords'] = 'Manufacturers Meta Keywords';
$_['manufacturer_url_keyword'] = 'Manufacturer Url Keywords';
$_['information_page_url_keyword'] = 'Information pages Url Keywords';
$_['information_page_title'] = 'Information pages Titles';
$_['information_meta_keywords'] = 'Informations Meta Keywords';
$_['information_meta_description'] = 'Information Meta Description';

// Dynamic description
$_['user_defined_text'] = '	<br>If you wish to add customized text write the text after of before the tags.<br>
							For best results seperate you text and predefined tags with a hyphen(-).<br>
							Example: [tag], -your text-, [tag]';

$_['user_defined_text_meta'] = 		'<br>If you wish to add customized text write the text after of before the tags.<br>
								 	For best results seperate you text and predefined tags with a comma(,).<br>
									Example: [tag], your text, [tag]';

$_['dynamic_main_description']	= '<p><b>Generate %s %s</b></p><br>%s';
$_['text_set_pattern']	= '- Set pattern of your choice in pattern box.<br>- See tags available and example.<br>- Click generate for auto generation.';

$_['text_general_data']	= '<p><b>General Page Seo Data</b></p><br>General Pages include home page, account page , checkout pages, extra pages, etc. <br><br><b><span style="color:green;">There are total of 48 general pages</span></b>';
$_['help_general_data']	= '<p><b><span style="color:green;">It Keeps Site Secured And Url Looks Cleaner</span></b></p>';
$_['help_general1_data']= 'See the change of url below: <br><b>http://store.nerdherd.in/index.php?route=account/register</b><br><b>http://store.nerdherd.in/register</b><br>OR<br><b>http://store.nerdherd.in/index.php?route=checkout/cart</b><br><b>http://store.nerdherd.in/cart';

$_['dymanic_text']	= 'Tags for use : %s';

$_['dymanic_text_image']	= 'Tags for use : %s';

// Note
$_['note_meta_description'] = '<b>Note:</b> First 120 characters of the %s description will be used to generate meta description.';


$_['howtouse'] = "How to use ?";

$_['help_product_generate_howtouse'] = "<h3>How to generate seo keyword for all products using generate button ?</h3>
You need to know something about <strong>patterns</strong>. And you can then do it easily<br>
<br>
<strong>Pattern : </strong>It is way of telling the auto generate feature what kind of pattern you want for seo keywords.
<br><br><i>Example Patterns: </i>
<ul>
 	<li>Model name - product name - custom text (.html)</li>
 	<li>Model name - product name</li>
 	<li>Product name - manufacturer name</li>
 	<li>Product name - manufacturer name - custom text (-best-deal)</li>
</ul>
<br><i>Generated Seo Keywords: </i>
<ul>
 	<li>128gb-iphone6s.html</li>
 	<li>128gb-iphone6s</li>
 	<li>iphone6s-apple</li>
 	<li>iphone6s-apple-best-deal</li>
</ul>
<br>
There can be many different patterns based on your needs.
<br>
So based on your need, you can add your pattern in input box and click generate.";


$_['help_category_generate_howtouse'] = "<h3>How to generate seo keyword for all categories using generate button ?</h3>
You need to know something about <strong>patterns</strong>. And you can then do it easily<br>
<br>
<strong>Pattern : </strong>It is way of telling the auto generate feature what kind of pattern you want for seo keywords.
<br><br><i>Example Patterns: </i>
<ul>
 	<li>[category_name], [meta_title]</li>
 	<li>[meta_title]</li>
 	<li>[category_name]</li>
</ul>
<br><i>Generated Seo Keywords: </i>
<ul>
 	<li>desktops-low-price-for-popular-products</li>
 	<li>low-price-for-popular-products</li>
 	<li>desktops</li>
</ul>
<br>
There can be many different patterns based on your needs.
<br>
So based on your need, you can add your pattern in input box and click generate.";


$_['help_manufacturer_generate_howtouse'] = "<h3>How to generate seo keyword for all manufacturers using generate button ?</h3>
You need to know something about <strong>patterns</strong>. And you can then do it easily<br>
<br>
<strong>Pattern : </strong>It is way of telling the auto generate feature what kind of pattern you want for seo keywords.
<br><br><i>Example Patterns: </i>
<ul>
 	<li>[manufacturer_name], [custom_text] (.html)</li>
 	<li>[manufacturer_name]</li>
</ul>
<br><i>Generated Seo Keywords: </i>
<ul>
 	<li>apple.html</li>
 	<li>apple</li>
</ul>
<br>
There can be many different patterns based on your needs.
<br>
So based on your need, you can add your pattern in input box and click generate.";

$_['help_information_generate_howtouse'] = "<h3>How to generate seo keyword for all manufacturers using generate button ?</h3>
You need to know something about <strong>patterns</strong>. And you can then do it easily<br>
<br>
<strong>Pattern : </strong>It is way of telling the auto generate feature what kind of pattern you want for seo keywords.
<br><br><i>Example Patterns: </i>
<ul>
 	<li> [information_page_title], [custom_text] (.html)</li>
 	<li>[information_page_title]</li>
</ul>
<br><i>Generated Seo Keywords: </i>
<ul>
 	<li>contant-us.html</li>
 	<li>contact-us</li>
</ul>
<br>
There can be many different patterns based on your needs.
<br>
So based on your need, you can add your pattern in input box and click generate.";


$_['help_general_generate_howtouse'] = "<h3>How to generate seo keyword for all general pages using generate button ?</h3>
Well our powerful algorithm easily creates for you all seo keywords for all general pages within seconds.
<br>
You only need to click generate button.<br><br>
And all you general links would created automatically.

<br><i>Examples: </i>
<ul>
 	<li>http://store.com/home</li>
 	<li>http://store.com/account</li>
 	<li>http://store.com/checkout</li>
 	<li>http://store.com/cart</li>
</ul>
<br>
<b>Our module shall make all possible general links that exists on your store </b>
<br>
<b>Once created you can visit seo advanced editor page for general links to check it </b>";